steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=subodaya
      - --key=sbd
  # Install dependencies
  - name: node
    entrypoint: yarn
    args: ['install']
  # Run custom commands
  - name: node
    entrypoint: yarn
    args: ['generate']
  # Deploy
  - name: 'gcr.io/ssss-ss/firebase'
    entrypoint: yarn
    args: ['deploy']
